EstoqueDeLivros.Web/Controllers/CadastrarController.cs
using EstoqueDeLivros.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstoqueDeLivros.Web.Controllers
{
    public class CadastrarController : Controller
    {

        [Authorize]
        public ActionResult Livro()
        {
            return View(LivroViewModel.ListaLivrosBanco());
        }

        [HttpPost]
        [Authorize]
        public ActionResult EditarLivro(int id)
        {
            return Json(LivroViewModel.Editar(id));
        }

        [HttpPost]
        [Authorize]
        public ActionResult ExcluirLivro(int id)
        {
            return Json(LivroViewModel.Excluir(id));
        }

        [HttpPost]
        [Authorize]
        public ActionResult SalvarLivro(LivroViewModel modelLivros)
        {
            var result = "OK!";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                result = "AVISO!";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x=>x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = modelLivros.Salvar();

                    if(id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        result = "ERRO!";
                    }
                }
                catch (Exception ex)
                {
                    result = "ERRO!";
                }
            }

            return Json(new { Result = result, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

EstoqueDeLivros.Web/Controllers/ContaController.cs
using EstoqueDeLivros.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EstoqueDeLivros.Web.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var achou = (UsuarioViewModel.ValidaUsuario(login.Usuario, login.Senha));

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);

                if (Url.IsLocalUrl(returnUrl))
                {
                    returnUrl = "/Cadastrar/Livro";
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login inválido!");
            }

            return View(login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

EstoqueDeLivros.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Estoque de Livros</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estoque de Livros", "Livro", "Cadastrar", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastrar
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Livro", "Livro", "Cadastrar")</li>
                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Olá @User.Identity.Name</a></li>

                            <li><a href="javascript:document.getElementById('logoffForm').submit()">Sair</a></li>

                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }


            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Estoque de Livros</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>